# Site settings
name: 某科学的程序员
email: 1411192769@qq.com
author: 黑水
url: https://bg25452.github.io./
resume_site: 暂无
github: https://github.com/bg25452/
baseurl: "/LessOrMore"
description: 御坂美琴一生
meta_description: 愚者不努力，懒人盼巅峰
motto: It's our wits that make us men.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: bg25452
highlighter: Pygments

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

FB:
  comments :
    provider : duoshuo
    duoshuo:
        short_name : bg25452
    disqus :
        short_name : freudkang
    # facebook :
    #   appid : 123
    #   num_posts: 5
    #   width: 580
    #   colorscheme: light
